name: Deploy Smart Home Platform

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Install CDK dependencies
        run: cd cdk && npm ci
      
      - name: Install AWS Amplify Alpha package
        run: |
          npm install @aws-cdk/aws-amplify-alpha
          cd cdk && npm install @aws-cdk/aws-amplify-alpha

      - name: Prepare schema.graphql
        run: |
          mkdir -p cdk/schema.graphql
          cp schema.graphql cdk/schema.graphql/schema.graphql

      - name: Build TypeScript
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Bootstrap CDK
        run: npx cdk bootstrap

      - name: Check stack status
        run: node check-stacks.js

      - name: Deploy stacks sequentially
        run: node deploy-sequential.js